### ISSUE TITLE
Bitlocker proactive remediation script

### ISSUE THREAD

**Issue by amirjs** [SuneThomsenDK/OSDSUNE#1]
Nice work and logic you have done there but I was just wondering what if a device is decrypted and re-encrypted by an admin (or the key was rotated) and for some reason, the keys weren't uploaded to Intune at the time? In this case, the script will not upload the new key to Intune because the registry key is already set to $true from a previous run.

**Comment by SuneThomsenDK** [comment]
Hi, and sorry for the late reply. I get your point :) 

However, this is meant to be a solution you use along with configuring BitLocker in Intune, which will take over the rotation and ensure the keys are uploaded again.

Both the event date and the registry will potentially block it from running again, but as I recall it you could change the event date and replace the reg value with something other than "true". - this should make the detection/remediation script run again :) 

BTW. Have you tried my latest version or my BETA? 

BR
Sune

**Comment by amirjs** [comment]
Thanks Sune - I used the original script and did some modifications to address the above :) It's already in prod and ticking nicely. Thanks again
